// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2OswLfOhis35B5DunZJvTap1BGhbSAc',
    appId: '1:595110888555:web:7c07cd42ad2a63d68c1d2e',
    messagingSenderId: '595110888555',
    projectId: 'tasty-79b68',
    authDomain: 'tasty-79b68.firebaseapp.com',
    storageBucket: 'tasty-79b68.appspot.com',
    measurementId: 'G-TJSGDBZVE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFh8w1vngKzglDnH3OlokCqV24WOCX-A',
    appId: '1:595110888555:android:066a04331f4309218c1d2e',
    messagingSenderId: '595110888555',
    projectId: 'tasty-79b68',
    storageBucket: 'tasty-79b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5EMMQJrxOXZL9a4FjM7i28zUBfJM-jw',
    appId: '1:595110888555:ios:606d499c8959fa248c1d2e',
    messagingSenderId: '595110888555',
    projectId: 'tasty-79b68',
    storageBucket: 'tasty-79b68.appspot.com',
    iosClientId: '595110888555-f1gu64mv1474a99obh9rnuoo6ui5p3cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr5EMMQJrxOXZL9a4FjM7i28zUBfJM-jw',
    appId: '1:595110888555:ios:606d499c8959fa248c1d2e',
    messagingSenderId: '595110888555',
    projectId: 'tasty-79b68',
    storageBucket: 'tasty-79b68.appspot.com',
    iosClientId: '595110888555-f1gu64mv1474a99obh9rnuoo6ui5p3cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyy',
  );
}
